name: Fetch Mastodon Statuses

on:
  schedule:
    - cron: "0 * * * *"  # Run every hour
  workflow_dispatch:  # Manual trigger

jobs:
  fetch_statuses:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # Update to a version that supports Node.js 20

    - name: Set up Python
      uses: actions/setup-python@v4.8.0  # Update to the latest version supporting Node.js 20
      with:
        python-version: '3.x'  # Ensure this matches your Python version requirement

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Fetch Mastodon statuses
      run: |
        python fetch_mastodon_status.py

    - name: List files in the repository
      run: |
        echo "Listing files in the current directory:"
        ls -al
        echo "Searching for status.json:"
        find . -name 'status.json'
        if [ -f status.json ]; then
          echo "status.json found! Content:"
          cat status.json
        else
          echo "status.json not found!"
        fi

    - name: Commit and push changes
      run: |
        echo "Configuring git user"
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        echo "Adding status.json to git"
        ls -al
        find . -name 'status.json'
        git add status.json || echo "status.json not found for git add"
        git commit -m 'Update status.json' || echo "No changes to commit"
        git push || echo "No changes to push"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
