name: Fetch Weather Data

on:
  schedule:
    - cron: '0 0 * * *' # 每天午夜执行一次
  workflow_dispatch: # 手动触发

jobs:
  fetch_weather:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4 # 确保使用最新版本

    - name: Set up Python
      uses: actions/setup-python@v4.7.0 # 确保使用支持 Node.js 20 的版本
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run weather fetch script
      run: python fetch_weather.py

    - name: List directory contents
      run: ls -la

    - name: Check if file exists
      run: |
        if [ -f historical_weather.json ]; then
          echo "historical_weather.json exists."
        else:
          echo "historical_weather.json does not exist."
